# SPDX-License-Identifier: Apache-2.0
sonar.projectKey=rdzehtsiar_hotpath
sonar.organization=raman-dzehtsiar
sonar.projectName=Hot Path
sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.rust.lcov.reportPaths=lcov.info
sonar.exclusions=target/**,qodana.sarif.json
